name=TS_lib
version=2.0.0
author=Filippo Raciti
maintainer=Filippo Raciti
sentence=Manage serial protocol from Arduino (or other kind of microcontrollers) to TunerStudio software
paragraph=This library can be used to connect Arduino (or other kind of microcontrollers) to TunerStudio software
category=Communication
url=https://github.com/filipporaciti/TS_lib.git
architectures=*
includes=TS_lib.h
depends=CRC32
