;-------------------------------------------------------------------------------
[MegaTune]
   MTversion      = 2.25
   queryCommand   = "Q"
   signature      = "TSlib_11-2025"
   versionInfo    = "S"

;-------------------------------------------------------------------------------
[TunerStudio]
   iniSpecVersion = 3.64

;-------------------------------------------------------------------------------
[Constants]
   endianness = little ; arduino => little endian
   nPages = 1
   blockingFactor = 240
   pageSize =           6
   pageIdentifier =     "\x00"
   pageReadCommand =    "p%2i%2o%2c"
   pageValueWrite =     "M%2i%2o%2c%v"
   crc32CheckCommand =  "d%2i"
   burnCommand =        "b%2i"

   delayAfterPortOpen=1000
   blockReadTimeout = 2000
   tsWriteBlocks = on
   pageActivationDelay = 10   

   ;  name                 = scalar, type,    offset,    units,  scale, translate, lo,  hi,                 digits
   page = 1 ; ID = 0
      crankTeeth           = scalar, U08,     0,         "teeth",    1,      0,    0,   255,                0
      crankMissingTeeth    = scalar, U08,     1,         "teeth",    1,      0,    0,   255,                0

      tpsMin               = scalar, U08,     2,         "ADC",      1,      0,    0,   255,                0
      tpsMax               = scalar, U08,     3,         "ADC",      1,      0,    0,   255,                0

      rpmMaxLimit          = scalar, U16,     4,         "rpm",      1,      0,    0,   20000,              0

;-------------------------------------------------------------------------------
[Menu]
menuDialog = main
   menu = "Settings"
      subMenu = settings,    "Settings"

;-------------------------------------------------------------------------------
[UserDefined]
   dialog = settings, "Settings"
      topicHelp = "http://localhost"
      field = "Crank teeth",     crankTeeth
      field = "Missing teeth",   crankMissingTeeth
      field = "RPM max limit",   rpmMaxLimit

;-------------------------------------------------------------------------------
[OutputChannels]
   ochGetCommand    = "A"
   ochBlockSize     =  12

   millisecond      = scalar,   U32,    0, "ms",     1,     0
   cyclesPerSecond  = scalar,   U32,    4, "ms",     1,     0
   rpm              = scalar,   U16,    8, "rpm",    1,     0
   tpsADC           = scalar,   U08,    10, "%",     1,     0
   synccnt          = scalar,   U08,    11, "",      1,     0

;-------------------------------------------------------------------------------
[GaugeConfigurations]
   gaugeCategory = "Basic Gauges"

   ;Name               Var                Title                      Units      Lo  Hi                   LoD    LoW  HiW                     HiD                     vd ld
   rpmGauge          = rpm,               "Engine Speed",            "RPM",     0,  10000,               300,   600, 8000,                   9000,                   0, 0
   tpsGauge          = tpsADC,            "TPS",                     "%",       0,  255,                 -1,    -1,  256,                    256,                    0, 0
   millisGauge       = millisecond,       "Alive microseconds",      "ms",      0,  4294967,             -1,    -1,  4294968,                4294968,                0, 0
   cyclesGauge       = cyclesPerSecond,   "Cycles per second",       "cycles",  0,  4294967,             -1,    -1,  4294968,                4294968,                0, 0
   lostSyncGauge     = synccnt,           "Crank Lost Sync Counter", "",        0,  255,                 256,   -1,  256,                    256,                    0, 0

;-------------------------------------------------------------------------------
[FrontPage]
   ; Ordered gauge configuration
   ;    1  2  3  4
   ;    5  6  7  8

   gauge = rpmGauge
   gauge = tpsGauge
   gauge = millisGauge
   gauge = cyclesGauge
   gauge = lostSyncGauge
   ; gauge = 
